# Generated by Django 3.2.15 on 2022-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Origin (country)'),
        ),
    ]
